#!/usr/bin/env python3

import time
import sys
import os

from optparse import OptionParser, IndentedHelpFormatter, OptionError

from dt import *
from dt_options import *

def  main():

    parser = OptionParser(
        option_class=DtOption,
        formatter=IndentedHelpFormatter(max_help_position=36),
        description="print Times and Durations",
        usage="""{0} [options]""".format(os.path.basename(sys.argv[0])),
    )

    parser.add_option("--time", "-t",
		metavar="T",
		dest="times",
		action="append",
		type="Time",
		default=[],
		help="add time")

    parser.add_option("--duration", "-d",
		metavar="D",
		dest="durations",
		action="append",
		type="Duration",
		default=[],
		help="add duration")


    (options, args) = parser.parse_args()

    times = options.times
    durations = options.durations
    strings = []
    for arg in args:
        try:
            dt = create_dt(arg)
        except:
            sys.stderr.write("ERR: invalid arg {0!r}\n".format(arg))
            sys.exit(1)
        else:
            if isinstance(dt, Time):
                l = options.times
            elif isinstance(dt, Duration):
                l = options.durations
            else:
                l = strings
            l.append(dt)
                
    for l in times, durations, strings:
        for i in l:
            print(repr(i)) #print("{0:10s} {1}".format(type(i).__name__, i))
 
if __name__ == "__main__":
    main()
